name: 🔄 Sync Airtable to listings.json (via PR)

on:
  schedule:
    - cron: "0 8 * * *" # Daily at 8AM UTC
  workflow_dispatch:

jobs:
  airtable-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Airtable data and update JSON
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.AIRTABLE_API_KEY }}" \
          "https://api.airtable.com/v0/${{ secrets.AIRTABLE_BASE_ID }}/${{ secrets.AIRTABLE_TABLE_NAME }}?maxRecords=1000" \
          | jq '.records | map({
              company: .fields.Company,
              role: .fields.Role,
              location: .fields.Location,
              link: .fields.Link
            })' > .github/scripts/listings.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🔄 Auto-update listings.json from Airtable"
          title: "🔄 Auto-update listings.json from Airtable"
          body: |
            This PR updates `.github/scripts/listings.json` with the latest internship data from Airtable.
          branch: auto/update-listings-${{ github.run_id }}
          base: main
